name: Run Python Unit Tests and Linter

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use latest Python 3

    - name: Install dependencies
      run: pip install -r requirements.txt || true

    - name: Run linter (flake8)
      run: |
        pip install flake8  # Install flake8 if it's not already in requirements.txt
        flake8 .  # Run flake8 to lint all Python files in the repository

    - name: Run unit tests
      run: python -m unittest discover
